---

# Check vars/main.yml to set distro-specific config file location
- name: Set the smartd configuration file path
  set_fact:
    smartd_config_path: "{{ smartd_possible_config_paths[ansible_distribution] | default(smartd_possible_config_paths.default) }}"

- name: Update repository cache (apt)
  apt:
    update_cache: yes
  changed_when: false
  when: "ansible_pkg_mgr == 'apt'"

- name: Update repository cache (pacman)
  pacman:
    update_cache: yes
  changed_when: false
  when: "ansible_pkg_mgr == 'pacman'"

- name: Install smartmontools package (apt)
  apt:
    name: smartmontools
  when: ansible_pkg_mgr == "apt"

- name: Install smartmontools package (pacman)
  pacman:
    name: smartmontools
  when: ansible_pkg_mgr == "pacman"

- name: Install smartmontools package (dnf)
  dnf:
    name: smartmontools
  when: ansible_pkg_mgr == "dnf"

- name: Create smartd configuration
  template:
    src: smartd.conf.j2
    dest: "{{ smartd_config_path }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: Restart smartd
...
