---
- name: Install smartmontools
  package:
    name: smartmontools
  when: ansible_pkg_mgr in ["apt", "pacman", "dnf", "yum", "pkgng"]

- name: Create smartd configuration
  template:
    src: smartd.conf.j2
    dest: "{{ smartd_config_path }}"
    owner: root
    group: "{{ smartd_file_group }}"
    mode: 0644
    validate: smartd -q onecheck -c %s
  notify: Restart smartd

- name: Enable smartd
  service:
    name: "{{ smartd_service_name }}"
    state: started
    enabled: yes
